### ISSUE TITLE
test drive feedback

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/geoknife#126]
as a total noob, the main pain points have been:

1) figuring out which dataset to choose and how to reference it and its variables
2) how to define a shape (webgeom("state::CO") is cool. so is webgeom('HUC8::09020306,14060009'). what are my other options?
3) how to cancel a job, or what to do instead, once i've messed it up

these are all documented in other issues, i think, so this list is just to point out the high priorities for a new user

**Comment by jread-usgs** [comment]
Thanks! :+1:

**Comment by jread-usgs** [comment]
- [ ] figuring out which dataset to choose and how to reference it and its variables (covered in #116 and #86?)
- [ ] how to define a shape? (should be covered in vignette #120 and in `webgeom` and `simplegeom` sections in there)
- [ ] how to cancel a job? Needs documentation, but covered in #130

**Comment by jread-usgs** [comment]
for the second comment here, having talked with @lawinslow too, for now, I am going to code in an error that lists all possible matches when there isn't a match for one of those quickstart character inputs for webgeom or webdata. I will reference this in the PR and see what you think.

**Comment by jread-usgs** [comment]
I think this is covered now, but I will be filling out the vignette #120
